### ISSUE TITLE
Add QuickSettings tile to toggle state

### ISSUE THREAD

**Issue by msfjarvis** [msfjarvis/Wireless_ADB#3]
Self-explanatory title I guess. I'll assist anybody willing to take this up until the finish.

**Comment by lelloman** [comment]
Hi, I'd like to pick up the task to celebrate hacktoberfest, I'm not 100% sure I understood what's to be done though.

**Comment by msfjarvis** [comment]
> Hi, I'd like to pick up the task to celebrate hacktoberfest, I'm not 100% sure I understood what's to be done though.

The tile just needs to run the [`{enable/disable}Adb`](https://github.com/msfjarvis/Wireless_ADB/blob/master/app/src/main/java/com/jmzsoftware/jmzwirelessadb/MainActivity.kt#L57-L63) methods on tap. To persist enabled/disabled state you can either let the QS tile lifecycle handle it (very undesirable) or check if the `service.adb.tcp.port` prop is `0` or empty for disabled and `5555` for enabled.

**Comment by lelloman** [comment]
OK, thanks for clarification, I'd like to give this a go. I think that reading the system property to determine the state would indeed be a more desirable solution.

**Comment by msfjarvis** [comment]
Fixed with #4, thanks for participating!
